spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/baseDeDatos_Proyecto?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      # Maximo tamaño permitido de subida
      max-file-size: 20MB
      max-request-size: 20MB
# Direccion en la que se guardan los documentos
documentos:
  upload-directory: doc-uploads
  