insert into materia(nombre, carrera, departamento, universidad) values("Historia de los sistemas", "Informatica", "Desarrollo Productivo y Tecnológico", "UNLa");
insert into materia(nombre, carrera, departamento, universidad) values("Matematicas avanzadas", "Fisica", "Desarrollo Productivo y Tecnológico", "UNQui");
insert into materia(nombre, carrera, departamento, universidad) values("Literatura", "Historia", "Humanidades y Artes", "UTN");
insert into userRole(role) values ('ROLE_ADMIN');
insert into userRole(role) values ('ROLE_PROFESOR');
insert into userRole(role) values ('ROLE_ALUMNO');
insert into user(email, enabled, password, username, userRole) values('mengano@gmail.com', true, '$2y$12$7p2RevsYeODhvje4Im8laOv0fR26Zcs8vUEck82VkAo6yuvbJ3xle', 'admin', 1);
insert into user(email, enabled, password, username, userRole) values('profesor@gmail.com', true, '$2y$12$BGp7FdCw6oxhWVMrM3xfxu1t8.P/aSQl6Q61X7euDQvwVTwzXxKKK', 'profesor', 2);
insert into user(email, enabled, password, username, userRole) values('alumno@gmail.com', true, '$2y$12$MfKtZvc8vHkxwppiFthL6ewrh4gryY0L.K1HZtVyBasqUVJPs/TWK', 'alumno', 3);
insert into materiaPorUser(id, idMateria) values(2, 1);
insert into materiaPorUser(id, idMateria) values(2, 3);
insert into documento(titulo, descripcion, profesor, materia, hashArchivo) values("La primera computadora", "Buen libro", "Jose", 1, "f976a72a75241b8adcfd971daeca69d8");
insert into documento(titulo, descripcion, profesor, materia, hashArchivo) values("Ecuaciones y ecuaciones", "Libro aburrido", "Pepe", 2, "61eb5c60adf662d188e512c0e067b48b");
insert into documento(titulo, descripcion, profesor, materia, hashArchivo) values("Historia de la literatura", "Libro denso", "Luis", 3, "fb499329311ca42711a574ccd9ac800f");
insert into review(valoracion, titulo, comentario, autor, documento) values(5, "Bastante decente", "Bastante completo el libro, me dejo satisfecho", 3, 1);
insert into review(valoracion, titulo, comentario, autor, documento) values(2, "Podria ser mejor", "No entendi nada, la verdad que el texto es muy complejo de la forma en que esta redactado.", 1, 1);